// UI 에셋 매니페스트
// ------------------------------------------------------------------
// 오버뷰 시트(8장)에 라벨링된 모든 UI 컴포넌트를 코드에서 참조 가능한 단일
// 소스로 정리한다. 각 항목은 "이 에셋이 어떤 화면/렌더 함수에서 쓰이는지"까지
// 포함하므로, 시트를 개별 PNG로 슬라이스한 뒤 `file` 경로에 넣기만 하면
// 바로 import 하여 사용할 수 있다.
//
// 개별 PNG가 `file` 경로에 배치되면 해당 항목의 `sliced`를 true로 둔다.
// 현재 프로젝트용 생성 에셋은 `scripts/generate-ui-assets.py`로 다시 만들 수 있다.
//
// 문서판(사람용 카탈로그): docs/ui-asset-catalog.md
// ------------------------------------------------------------------

/** 원본 오버뷰 시트 식별자 */
export type SheetId =
  | "sheet-a-right-panel" //  우측 패널 / 미션 / 보스
  | "sheet-b-battlefield" //  전장 프레임 / 데미지미터 / 웨이브 경로
  | "sheet-c-actionbar" //    하단 액션바 / 버튼 / 보스 경고
  | "sheet-d-layout-kit" //   레이아웃 프리뷰 / 공용 프레임·버튼 키트
  | "sheet-e-topbar" //       상단 상태바 / 배지 / 속도 컨트롤
  | "sheet-f-slots-popups" // 슬롯 / 게이지 바 / 팝업
  | "sheet-g-units" //        보유 유닛 리스트 / 유닛 카드 / 필터
  | "sheet-h-unit-detail"; // 선택 유닛 상세 패널

/** 슬라이스 후 저장될 카테고리 폴더 (src/assets/ui/<category>/) */
export type AssetCategory =
  | "frames" //       패널/나인슬라이스/코너/디바이더/배지 베이스
  | "buttons" //      액션·탭·범용 버튼, 속도 버튼
  | "topbar" //       상단 상태바, 정보 배지, 헤더 아이콘
  | "units" //        유닛 카드, 필터, 속성/등급 아이콘, 용량 바
  | "unit-detail" //  선택 유닛 상세 패널 부품
  | "mission" //      미션 카드, 배너, 플레이트
  | "boss" //         보스 정보/카드/보상/경고
  | "battlefield" //  전장 프레임, 길, 마커, 웨이브 노드
  | "meters" //       데미지미터, HP/MP/보스 바, 진행 바
  | "slots" //        스킬/아이템/장비/유물/효과/빈/잠금 슬롯
  | "popups" //       확인/보상/설정/툴팁/보스 경고 팝업
  | "controls" //     체크박스, 토글, 커서
  | "fx"; //          글로우 등 이펙트

export interface UiAsset {
  /** 코드에서 쓰는 고유 키 (점 네임스페이스) */
  key: string;
  /** 사람이 읽는 이름 */
  label: string;
  sheet: SheetId;
  category: AssetCategory;
  /** 슬라이스 결과물이 놓일 경로 (src/assets/ui 기준 상대) */
  file: string;
  /** 적용 위치: src/ui 모듈과 렌더 함수(COMPONENT) */
  usage: {
    module: string;
    component: string;
    /** 어떤 상태/용도로 쓰이는지 */
    note: string;
  }[];
  /** 9-슬라이스로 늘려 쓰는 프레임/바 계열인가 */
  nineSlice?: boolean;
  /**
   * 9-슬라이스 모서리 inset(px). 늘어나지 않는 테두리 두께.
   * 단일 값이면 4변 동일, [상,우,하,좌]면 변별 지정. 미지정 시 헬퍼 기본값 사용.
   * 슬라이스 후 실제 에셋에 맞게 채운다.
   */
  border?: number | [number, number, number, number];
  /** 동일 비주얼의 상태 변형(normal/hover/selected 등) 묶음 키 */
  variantGroup?: string;
  /** 실제 PNG 슬라이스 완료 여부 */
  sliced: boolean;
}

const A: SheetId = "sheet-a-right-panel";
const B: SheetId = "sheet-b-battlefield";
const C: SheetId = "sheet-c-actionbar";
const D: SheetId = "sheet-d-layout-kit";
const E: SheetId = "sheet-e-topbar";
const F: SheetId = "sheet-f-slots-popups";
const G: SheetId = "sheet-g-units";
const H: SheetId = "sheet-h-unit-detail";

/** 모든 UI 에셋. key로 조회한다. */
export const UI_ASSETS: UiAsset[] = [
  // ===================== Sheet D — 공용 레이아웃/프레임·버튼 키트 =====================
  // (가장 먼저 적용해야 하는 기반 에셋. 거의 모든 패널/버튼이 여기서 파생된다.)
  {
    key: "frame.panel.main",
    label: "Fantasy Main Panel",
    sheet: D,
    category: "frames",
    file: "frames/panel-main.png",
    nineSlice: true,
    sliced: true,
    usage: [
      { module: "src/ui/widgets.ts", component: "openModal/ModalShell", note: "큰 모달 배경 (panel-frame.svg 대체)" },
      { module: "src/ui/panels.ts", component: "renderRightPanel", note: "우측 탭 셸 배경" },
    ],
  },
  {
    key: "frame.panel.small",
    label: "Fantasy Small Panel",
    sheet: D,
    category: "frames",
    file: "frames/panel-small.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderRightPanel(BossTab/LogTab)", note: "작은 정보 패널 배경" }],
  },
  {
    key: "frame.nineslice.main",
    label: "Main Nine-Slice Panel",
    sheet: D,
    category: "frames",
    file: "frames/nineslice-main.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/widgets.ts", component: "el()/공용", note: "가변 크기 패널을 9-슬라이스로 늘릴 때 베이스" }],
  },
  {
    key: "frame.nineslice.small",
    label: "Small Nine-Slice Panel",
    sheet: D,
    category: "frames",
    file: "frames/nineslice-small.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/widgets.ts", component: "el()/공용", note: "작은 가변 패널 베이스" }],
  },
  {
    key: "btn.generic.normal",
    label: "Button Normal",
    sheet: D,
    category: "buttons",
    variantGroup: "btn.generic",
    file: "buttons/generic-normal.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "TitleMenu/PauseMenu/OptionsOverlay", note: "범용 버튼 기본 상태" }],
  },
  {
    key: "btn.generic.hover",
    label: "Button Hover",
    sheet: D,
    category: "buttons",
    variantGroup: "btn.generic",
    file: "buttons/generic-hover.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "공용 버튼 :hover", note: "마우스 오버 상태" }],
  },
  {
    key: "btn.generic.pressed",
    label: "Button Pressed",
    sheet: D,
    category: "buttons",
    variantGroup: "btn.generic",
    file: "buttons/generic-pressed.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "공용 버튼 :active", note: "눌림 상태" }],
  },
  {
    key: "btn.tab.normal",
    label: "Tab Button Normal",
    sheet: D,
    category: "buttons",
    variantGroup: "btn.tab",
    file: "buttons/tab-normal.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderRightPanel", note: "INFO/MISSION/RELICS 비선택 탭" }],
  },
  {
    key: "btn.tab.selected",
    label: "Tab Button Selected",
    sheet: D,
    category: "buttons",
    variantGroup: "btn.tab",
    file: "buttons/tab-selected.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderRightPanel", note: "현재 선택된 탭" }],
  },
  {
    key: "frame.badge",
    label: "Fantasy Badge",
    sheet: D,
    category: "frames",
    file: "frames/badge.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "좌상단 앱/길드 엠블럼" }],
  },
  {
    key: "frame.divider",
    label: "Fantasy Divider",
    sheet: D,
    category: "frames",
    file: "frames/divider.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "공용", note: "패널 내 섹션 구분선" }],
  },
  {
    key: "frame.corner",
    label: "Fantasy Frame Corner",
    sheet: D,
    category: "frames",
    file: "frames/corner.png",
    sliced: true,
    usage: [{ module: "src/ui/widgets.ts", component: "9-슬라이스 코너", note: "프레임 네 모서리 장식" }],
  },
  {
    key: "fx.glow.set",
    label: "Fantasy Glow Effect (blue/fire/ripple)",
    sheet: D,
    category: "fx",
    file: "fx/glow-set.png",
    sliced: true,
    usage: [
      { module: "src/ui/board.ts", component: "BoardRenderer", note: "유닛 선택/스킬 발동 글로우" },
      { module: "src/ui/panels.ts", component: "renderActionbar", note: "사용 가능 버튼 강조" },
    ],
  },

  // ===================== Sheet E — 상단 상태바 =====================
  {
    key: "topbar.bar",
    label: "Top Status Bar",
    sheet: E,
    category: "topbar",
    file: "topbar/status-bar.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "상단 상태바 전체 배경" }],
  },
  {
    key: "topbar.badge.map",
    label: "Map Info Badge",
    sheet: E,
    category: "topbar",
    file: "topbar/badge-map.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "현재 맵/스테이지 표시" }],
  },
  {
    key: "topbar.badge.round",
    label: "Round Info Badge",
    sheet: E,
    category: "topbar",
    file: "topbar/badge-round.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "현재 라운드 수" }],
  },
  {
    key: "topbar.badge.enemy",
    label: "Enemy Count Badge",
    sheet: E,
    category: "topbar",
    file: "topbar/badge-enemy.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "남은 적 수" }],
  },
  {
    key: "topbar.badge.gold",
    label: "Gold Info Badge",
    sheet: E,
    category: "topbar",
    file: "topbar/badge-gold.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "보유 골드" }],
  },
  {
    key: "topbar.badge.difficulty",
    label: "Difficulty Badge",
    sheet: E,
    category: "topbar",
    file: "topbar/badge-difficulty.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "난이도 표시" }],
  },
  {
    key: "topbar.badge.next-boss",
    label: "Next Boss Badge",
    sheet: E,
    category: "topbar",
    file: "topbar/badge-next-boss.png",
    sliced: true,
    usage: [
      { module: "src/ui/panels.ts", component: "renderTopbar", note: "다음 보스까지 카운트다운" },
      { module: "src/ui/panels.ts", component: "renderRightPanel(BossTab)", note: "보스 예고 헤더" },
    ],
  },
  {
    key: "topbar.speed.group",
    label: "Speed Control Group",
    sheet: E,
    category: "topbar",
    file: "topbar/speed-group.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "x1/x2/x3 묶음 프레임" }],
  },
  {
    key: "topbar.speed.x1",
    label: "Speed Button x1",
    sheet: E,
    category: "topbar",
    variantGroup: "topbar.speed",
    file: "topbar/speed-x1.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "1배속" }],
  },
  {
    key: "topbar.speed.x2",
    label: "Speed Button x2",
    sheet: E,
    category: "topbar",
    variantGroup: "topbar.speed",
    file: "topbar/speed-x2.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "2배속" }],
  },
  {
    key: "topbar.speed.x3-selected",
    label: "Speed Button x3 Selected",
    sheet: E,
    category: "topbar",
    variantGroup: "topbar.speed",
    file: "topbar/speed-x3-selected.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "선택된 배속 강조(금색)" }],
  },
  {
    key: "topbar.btn.pause",
    label: "Pause Button",
    sheet: E,
    category: "topbar",
    file: "topbar/btn-pause.png",
    sliced: true,
    usage: [
      { module: "src/ui/panels.ts", component: "renderTopbar", note: "일시정지 토글" },
      { module: "src/ui/scenes.ts", component: "openPauseMenu", note: "일시정지 메뉴 진입" },
    ],
  },
  {
    key: "topbar.save-indicator",
    label: "Save Status Indicator",
    sheet: E,
    category: "topbar",
    file: "topbar/save-indicator.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "자동 저장 상태(저장 중/완료)" }],
  },
  {
    key: "topbar.divider.tiny",
    label: "Tiny Status Divider",
    sheet: E,
    category: "topbar",
    file: "topbar/divider-tiny.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "상태바 항목 간 구분" }],
  },
  {
    key: "topbar.icons.header-set",
    label: "Header Icon Set (map/round/enemy/gold/difficulty/boss)",
    sheet: E,
    category: "topbar",
    file: "topbar/header-icons.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderTopbar", note: "각 정보 배지의 아이콘 6종" }],
  },

  // ===================== Sheet C — 하단 액션바 =====================
  {
    key: "actionbar.bar",
    label: "Bottom Action Bar",
    sheet: C,
    category: "buttons",
    file: "buttons/actionbar.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "하단 액션바 전체 배경(슬롯 8칸 + 라운드)" }],
  },
  {
    key: "actionbar.btn.summon",
    label: "Action Button Summon",
    sheet: C,
    category: "buttons",
    file: "buttons/action-summon.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "유닛 소환" }],
  },
  {
    key: "actionbar.btn.merge",
    label: "Action Button Merge",
    sheet: C,
    category: "buttons",
    file: "buttons/action-merge.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "유닛 합성" }],
  },
  {
    key: "actionbar.btn.sell",
    label: "Action Button Sell",
    sheet: C,
    category: "buttons",
    file: "buttons/action-sell.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "유닛 판매" }],
  },
  {
    key: "actionbar.btn.upgrade",
    label: "Action Button Upgrade",
    sheet: C,
    category: "buttons",
    file: "buttons/action-upgrade.png",
    sliced: true,
    usage: [
      { module: "src/ui/panels.ts", component: "renderActionbar", note: "업그레이드 진입" },
      { module: "src/ui/panels.ts", component: "UpgradeModal", note: "패밀리 업그레이드 모달 트리거" },
    ],
  },
  {
    key: "actionbar.btn.relic",
    label: "Action Button Relic",
    sheet: C,
    category: "buttons",
    file: "buttons/action-relic.png",
    sliced: true,
    usage: [
      { module: "src/ui/panels.ts", component: "renderActionbar", note: "유물 패널 열기" },
      { module: "src/ui/modals.ts", component: "openRelicChoiceModal", note: "유물 선택 진입" },
    ],
  },
  {
    key: "actionbar.btn.dps-toggle",
    label: "Action Button DPS Toggle",
    sheet: C,
    category: "buttons",
    file: "buttons/action-dps-toggle.png",
    sliced: true,
    usage: [{ module: "src/ui/dpsMeter.ts", component: "toggleDps", note: "데미지미터 ON/OFF (DPS: OFF 라벨)" }],
  },
  {
    key: "actionbar.btn.round-start.normal",
    label: "Round Start Button Normal",
    sheet: C,
    category: "buttons",
    variantGroup: "actionbar.round-start",
    file: "buttons/round-start-normal.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "다음 웨이브 시작 (START ROUND)" }],
  },
  {
    key: "actionbar.btn.round-start.hover",
    label: "Round Start Button Hover",
    sheet: C,
    category: "buttons",
    variantGroup: "actionbar.round-start",
    file: "buttons/round-start-hover.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "START ROUND :hover" }],
  },
  {
    key: "actionbar.label.shortcut",
    label: "Action Shortcut Label",
    sheet: C,
    category: "buttons",
    file: "buttons/label-shortcut.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "단축키 + 액션명 칩 (예: 1 Summon Unit)" }],
  },
  {
    key: "actionbar.label.cost",
    label: "Action Cost Label",
    sheet: C,
    category: "buttons",
    file: "buttons/label-cost.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "마나/골드 비용 표시" }],
  },
  {
    key: "actionbar.btn.disabled",
    label: "Action Button Disabled",
    sheet: C,
    category: "buttons",
    file: "buttons/action-disabled.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderActionbar", note: "자원 부족 등 비활성 상태(회색)" }],
  },
  {
    key: "btn.primary",
    label: "Primary Action Button (BATTLE)",
    sheet: C,
    category: "buttons",
    variantGroup: "btn.cta",
    file: "buttons/primary.png",
    nineSlice: true,
    sliced: true,
    usage: [
      { module: "src/ui/scenes.ts", component: "TitleMenu", note: "주요 CTA (게임 시작 등)" },
      { module: "src/ui/modals.ts", component: "openNewRunModal", note: "확정/시작 버튼" },
    ],
  },
  {
    key: "btn.secondary",
    label: "Secondary Action Button (DEFEND)",
    sheet: C,
    category: "buttons",
    variantGroup: "btn.cta",
    file: "buttons/secondary.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "TitleMenu/모달", note: "보조 CTA" }],
  },

  // ===================== Sheet B — 전장 / 데미지미터 =====================
  {
    key: "battlefield.frame",
    label: "Battlefield Panel Frame",
    sheet: B,
    category: "battlefield",
    file: "battlefield/frame.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "전장 캔버스를 감싸는 외곽 프레임" }],
  },
  {
    key: "battlefield.road-border",
    label: "Battleroad Border Sample",
    sheet: B,
    category: "battlefield",
    file: "battlefield/road-border.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "적 이동 경로(길) 테두리 타일" }],
  },
  {
    key: "battlefield.enemy-path-marker",
    label: "Enemy Path Marker",
    sheet: B,
    category: "battlefield",
    file: "battlefield/enemy-path-marker.png",
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "진행 방향 화살표 마커" }],
  },
  {
    key: "battlefield.enemy-marker.normal",
    label: "Enemy Marker Normal",
    sheet: B,
    category: "battlefield",
    variantGroup: "battlefield.enemy-marker",
    file: "battlefield/enemy-marker-normal.png",
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "일반 적 위치 마커" }],
  },
  {
    key: "battlefield.enemy-marker.elite",
    label: "Enemy Marker Elite",
    sheet: B,
    category: "battlefield",
    variantGroup: "battlefield.enemy-marker",
    file: "battlefield/enemy-marker-elite.png",
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "정예 적 위치 마커" }],
  },
  {
    key: "battlefield.placement-node",
    label: "Unit Placement Node",
    sheet: B,
    category: "battlefield",
    file: "battlefield/placement-node.png",
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "유닛 배치 가능 위치 표시(+)" }],
  },
  {
    key: "battlefield.placed-unit-marker",
    label: "Placed Unit Marker",
    sheet: B,
    category: "battlefield",
    variantGroup: "battlefield.unit-marker",
    file: "battlefield/placed-unit-marker.png",
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "배치된 유닛 베이스 마커" }],
  },
  {
    key: "battlefield.selected-unit-marker",
    label: "Selected Unit Marker",
    sheet: B,
    category: "battlefield",
    variantGroup: "battlefield.unit-marker",
    file: "battlefield/selected-unit-marker.png",
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "선택된 유닛 강조(글로우)" }],
  },
  {
    key: "meters.damage-panel",
    label: "Damage Meter Panel",
    sheet: B,
    category: "meters",
    file: "meters/damage-panel.png",
    nineSlice: true,
    sliced: true,
    usage: [
      { module: "src/ui/dpsMeter.ts", component: "renderDpsMeter", note: "데미지미터 패널 배경" },
      { module: "src/ui/panels.ts", component: "renderRightPanel(INFO)", note: "INFO 탭의 DAMAGE TYPE 영역" },
    ],
  },
  {
    key: "meters.damage-row",
    label: "Damage Meter Row",
    sheet: B,
    category: "meters",
    file: "meters/damage-row.png",
    sliced: true,
    usage: [{ module: "src/ui/dpsMeter.ts", component: "renderDpsMeter", note: "유닛별 한 줄(초상화+이름+수치+%)" }],
  },
  {
    key: "meters.damage-bar.green",
    label: "Damage Meter Bar Green",
    sheet: B,
    category: "meters",
    variantGroup: "meters.damage-bar",
    file: "meters/damage-bar-green.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/dpsMeter.ts", component: "renderDpsMeter", note: "1위/높은 기여도 바" }],
  },
  {
    key: "meters.damage-bar.blue",
    label: "Damage Meter Bar Blue",
    sheet: B,
    category: "meters",
    variantGroup: "meters.damage-bar",
    file: "meters/damage-bar-blue.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/dpsMeter.ts", component: "renderDpsMeter", note: "중간 기여도 바" }],
  },
  {
    key: "meters.damage-bar.orange",
    label: "Damage Meter Bar Orange",
    sheet: B,
    category: "meters",
    variantGroup: "meters.damage-bar",
    file: "meters/damage-bar-orange.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/dpsMeter.ts", component: "renderDpsMeter", note: "낮은 기여도 바" }],
  },
  {
    key: "battlefield.mini-info-panel",
    label: "Mini Info Panel",
    sheet: B,
    category: "battlefield",
    file: "battlefield/mini-info-panel.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "유닛 호버 시 떠오르는 미니 정보 툴팁" }],
  },
  {
    key: "battlefield.wave-route-nodes",
    label: "Wave Route Node Set (start/normal/elite/boss/end)",
    sheet: B,
    category: "battlefield",
    file: "battlefield/wave-route-nodes.png",
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "웨이브 진행 단계 노드(스테이지 미니맵)" }],
  },

  // ===================== Sheet G — 보유 유닛 리스트 =====================
  {
    key: "units.list-panel",
    label: "Unit List Panel",
    sheet: G,
    category: "units",
    file: "units/list-panel.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "좌측 보유 유닛 패널 배경(UNITS 헤더)" }],
  },
  {
    key: "units.capacity-bar",
    label: "Unit Capacity Bar",
    sheet: G,
    category: "units",
    file: "units/capacity-bar.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "보유/최대 유닛 수(예: 12/40) + 추가 버튼" }],
  },
  {
    key: "units.filter-tabs",
    label: "Unit Filter Tabs",
    sheet: G,
    category: "units",
    file: "units/filter-tabs.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "속성 필터 탭 묶음(ALL/속성6종)" }],
  },
  {
    key: "units.filter-btn.normal",
    label: "Unit Filter Button Normal",
    sheet: G,
    category: "units",
    variantGroup: "units.filter-btn",
    file: "units/filter-btn-normal.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "그리드/필터 토글 비선택" }],
  },
  {
    key: "units.filter-btn.selected",
    label: "Unit Filter Button Selected",
    sheet: G,
    category: "units",
    variantGroup: "units.filter-btn",
    file: "units/filter-btn-selected.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "그리드/필터 토글 선택" }],
  },
  {
    key: "units.card.normal",
    label: "Unit Card Normal",
    sheet: G,
    category: "units",
    variantGroup: "units.card",
    file: "units/card-normal.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "일반 등급 유닛 카드" }],
  },
  {
    key: "units.card.selected",
    label: "Unit Card Selected",
    sheet: G,
    category: "units",
    variantGroup: "units.card",
    file: "units/card-selected.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "선택된 카드(파란 글로우 테두리)" }],
  },
  {
    key: "units.card.rare",
    label: "Unit Card Rare",
    sheet: G,
    category: "units",
    variantGroup: "units.card",
    file: "units/card-rare.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "레어 등급 카드(파란 테두리)" }],
  },
  {
    key: "units.card.legendary",
    label: "Unit Card Legendary",
    sheet: G,
    category: "units",
    variantGroup: "units.card",
    file: "units/card-legendary.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "전설 등급 카드(보라 테두리)" }],
  },
  {
    key: "units.element-icons",
    label: "Unit Element Icon Set (ice/fire/nature/holy/warrior/arcane)",
    sheet: G,
    category: "units",
    file: "units/element-icons.png",
    sliced: true,
    usage: [
      { module: "src/ui/panels.ts", component: "renderLeftPanel/UnitDetail", note: "유닛 속성 아이콘 6종" },
      { module: "src/ui/panels.ts", component: "renderLeftPanel", note: "필터 탭 아이콘과 공유" },
    ],
  },
  {
    key: "units.grade-badges",
    label: "Unit Grade Badge Set (normal/rare/epic/legendary)",
    sheet: G,
    category: "units",
    file: "units/grade-badges.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel/UnitDetail", note: "등급 배지 4종" }],
  },
  {
    key: "units.count-badge",
    label: "Unit Count Badge",
    sheet: G,
    category: "units",
    file: "units/count-badge.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "동일 유닛 보유 수(예: 99)" }],
  },
  {
    key: "units.tag-chip",
    label: "Unit Tag Chip",
    sheet: G,
    category: "units",
    file: "units/tag-chip.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel/UnitDetail", note: "역할/태그 칩(예: Frontline)" }],
  },
  {
    key: "units.btn.equip-small",
    label: "Equip Button Small",
    sheet: G,
    category: "units",
    file: "units/btn-equip-small.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "카드 내 장착 버튼" }],
  },
  {
    key: "units.selected-card-frame",
    label: "Selected Unit Card Frame",
    sheet: G,
    category: "units",
    file: "units/selected-card-frame.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderLeftPanel", note: "선택 카드 오버레이 프레임(애니메이션 테두리)" }],
  },

  // ===================== Sheet H — 선택 유닛 상세 패널 =====================
  {
    key: "unit-detail.panel",
    label: "Selected Unit Panel",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/panel.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "선택 유닛 상세 HUD 전체 배경" }],
  },
  {
    key: "unit-detail.portrait-frame",
    label: "Selected Unit Portrait Frame",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/portrait-frame.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "유닛 초상화 프레임" }],
  },
  {
    key: "unit-detail.name-plate",
    label: "Selected Unit Name Plate",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/name-plate.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "유닛 이름 배너" }],
  },
  {
    key: "unit-detail.grade-frame",
    label: "Selected Unit Grade Frame",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/grade-frame.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "등급 엠블럼 + 별점" }],
  },
  {
    key: "unit-detail.attack-power",
    label: "Attack Power Display",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/attack-power.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "공격력 대형 수치(예: 540)" }],
  },
  {
    key: "unit-detail.attack-type.magic",
    label: "Attack Type Badge Magic",
    sheet: H,
    category: "unit-detail",
    variantGroup: "unit-detail.attack-type",
    file: "unit-detail/attack-type-magic.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "마법 공격 타입 배지" }],
  },
  {
    key: "unit-detail.attack-type.physical",
    label: "Attack Type Badge Physical",
    sheet: H,
    category: "unit-detail",
    variantGroup: "unit-detail.attack-type",
    file: "unit-detail/attack-type-physical.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "물리 공격 타입 배지" }],
  },
  {
    key: "unit-detail.stat-grid",
    label: "Unit Stat Grid Frame",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/stat-grid.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "ATK/DEF/HP/SPD 등 스탯 격자" }],
  },
  {
    key: "unit-detail.stat-item",
    label: "Unit Stat Item Small",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/stat-item.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "스탯 한 칸(아이콘+라벨+값)" }],
  },
  {
    key: "unit-detail.tag-badges",
    label: "Unit Tag Badge Set",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/tag-badges.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "종족/속성/레벨/별 등 태그 배지" }],
  },
  {
    key: "unit-detail.effect-slot-grid",
    label: "Unit Effect Slot Grid",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/effect-slot-grid.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "버프/효과 슬롯 가로 그리드" }],
  },
  {
    key: "unit-detail.effect-slot",
    label: "Unit Effect Slot",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/effect-slot.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "단일 효과 슬롯" }],
  },
  {
    key: "unit-detail.effect-icons",
    label: "Unit Effect Icon Set",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/effect-icons.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "효과 아이콘 6종(아케인/물/자연/화염/방어/파동)" }],
  },
  {
    key: "unit-detail.effect-value-badge",
    label: "Unit Effect Value Badge",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/effect-value-badge.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "효과 지속시간/수치(예: 12s)" }],
  },
  {
    key: "unit-detail.bonus-tag-strip",
    label: "Bonus Tag Strip",
    sheet: H,
    category: "unit-detail",
    file: "unit-detail/bonus-tag-strip.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "보너스 태그 연결 스트립" }],
  },

  // ===================== Sheet A — 우측 패널 / 미션 / 보스 =====================
  {
    key: "right.side-panel",
    label: "Right Side Panel",
    sheet: A,
    category: "frames",
    file: "frames/right-side-panel.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderRightPanel", note: "우측 INFO/MISSION/RELICS 통합 패널" }],
  },
  {
    key: "right.tabs",
    label: "Right Panel Tabs",
    sheet: A,
    category: "frames",
    file: "frames/right-tabs.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderRightPanel", note: "INFO/MISSION/RELICS 탭 묶음" }],
  },
  {
    key: "right.tab-btn.normal",
    label: "Right Panel Tab Button Normal",
    sheet: A,
    category: "buttons",
    variantGroup: "right.tab-btn",
    file: "buttons/right-tab-normal.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderRightPanel", note: "비선택 우측 탭" }],
  },
  {
    key: "right.tab-btn.selected",
    label: "Right Panel Tab Button Selected",
    sheet: A,
    category: "buttons",
    variantGroup: "right.tab-btn",
    file: "buttons/right-tab-selected.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderRightPanel", note: "선택된 우측 탭(파란색)" }],
  },
  {
    key: "mission.card.active",
    label: "Mission Card Active",
    sheet: A,
    category: "mission",
    variantGroup: "mission.card",
    file: "mission/card-active.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "MissionTab", note: "진행 중 미션 카드" }],
  },
  {
    key: "mission.card.completed",
    label: "Mission Card Completed",
    sheet: A,
    category: "mission",
    variantGroup: "mission.card",
    file: "mission/card-completed.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "MissionTab", note: "완료 미션 카드(초록)" }],
  },
  {
    key: "mission.title-banner",
    label: "Mission Title Banner",
    sheet: A,
    category: "mission",
    file: "mission/title-banner.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "MissionTab", note: "미션 제목 배너" }],
  },
  {
    key: "mission.round-limit-badge",
    label: "Mission Round Limit Badge",
    sheet: A,
    category: "mission",
    file: "mission/round-limit-badge.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "MissionTab", note: "라운드 제한 수치 배지" }],
  },
  {
    key: "mission.progress-plate",
    label: "Mission Progress Plate",
    sheet: A,
    category: "mission",
    file: "mission/progress-plate.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "MissionTab", note: "진행도 플레이트(예: 2/4)" }],
  },
  {
    key: "mission.reward-plate",
    label: "Mission Reward Plate",
    sheet: A,
    category: "mission",
    file: "mission/reward-plate.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "MissionTab", note: "보상(골드+XP) 플레이트" }],
  },
  {
    key: "mission.completed-badge",
    label: "Mission Completed Badge",
    sheet: A,
    category: "mission",
    file: "mission/completed-badge.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "MissionTab", note: "완료 체크 배지(초록)" }],
  },
  {
    key: "boss.info-panel",
    label: "Boss Info Panel",
    sheet: A,
    category: "boss",
    file: "boss/info-panel.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "BossTab", note: "보스 상세(초상화+레벨+타입/약점/저항)" }],
  },
  {
    key: "boss.card",
    label: "Boss Card",
    sheet: A,
    category: "boss",
    file: "boss/card.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "BossTab", note: "다음 보스 예고 카드(진행 %)" }],
  },
  {
    key: "boss.reward-preview",
    label: "Boss Reward Preview",
    sheet: A,
    category: "boss",
    file: "boss/reward-preview.png",
    nineSlice: true,
    sliced: true,
    usage: [
      { module: "src/ui/panels.ts", component: "BossTab", note: "보스 처치 예상 보상 미리보기" },
      { module: "src/ui/modals.ts", component: "openRelicChoiceModal", note: "보상 후보 표시와 공유 가능" },
    ],
  },
  {
    key: "log.entry",
    label: "Log Entry",
    sheet: A,
    category: "frames",
    file: "frames/log-entry.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "LogTab", note: "게임 로그 한 줄(시각+이벤트)" }],
  },
  {
    key: "relic.panel-small",
    label: "Relic Panel Small",
    sheet: A,
    category: "slots",
    file: "slots/relic-panel-small.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderRightPanel(RELICS)", note: "RELICS 탭의 유물 슬롯 2칸" }],
  },

  // ===================== Sheet F — 슬롯 / 게이지 / 팝업 =====================
  {
    key: "slots.skill",
    label: "Skill Slot",
    sheet: F,
    category: "slots",
    variantGroup: "slots.skill",
    file: "slots/skill.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail/Actionbar", note: "스킬 아이콘 슬롯" }],
  },
  {
    key: "slots.skill-selected",
    label: "Selected Skill Slot",
    sheet: F,
    category: "slots",
    variantGroup: "slots.skill",
    file: "slots/skill-selected.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail/Actionbar", note: "선택된 스킬 슬롯(금색 프레임)" }],
  },
  {
    key: "slots.cooldown-overlay",
    label: "Cooldown Overlay",
    sheet: F,
    category: "slots",
    file: "slots/cooldown-overlay.png",
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer/스킬 슬롯", note: "쿨다운 회전 오버레이 + 남은 초" }],
  },
  {
    key: "slots.item",
    label: "Item Slot",
    sheet: F,
    category: "slots",
    file: "slots/item.png",
    sliced: true,
    usage: [{ module: "src/ui/modals.ts", component: "인벤토리/보상", note: "소비 아이템 슬롯(수량 표시)" }],
  },
  {
    key: "slots.equipment",
    label: "Equipment Slot",
    sheet: F,
    category: "slots",
    file: "slots/equipment.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "장비 슬롯" }],
  },
  {
    key: "slots.relic",
    label: "Relic Slot",
    sheet: F,
    category: "slots",
    file: "slots/relic.png",
    sliced: true,
    usage: [
      { module: "src/ui/panels.ts", component: "renderRightPanel(RELICS)", note: "유물 슬롯" },
      { module: "src/ui/modals.ts", component: "openRelicChoiceModal", note: "유물 선택 그리드" },
    ],
  },
  {
    key: "slots.effect",
    label: "Effect Slot",
    sheet: F,
    category: "slots",
    file: "slots/effect.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "버프/디버프 효과 슬롯" }],
  },
  {
    key: "slots.empty",
    label: "Empty Slot",
    sheet: F,
    category: "slots",
    variantGroup: "slots.state",
    file: "slots/empty.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "공용 슬롯", note: "빈 슬롯 기본" }],
  },
  {
    key: "slots.locked",
    label: "Locked Slot",
    sheet: F,
    category: "slots",
    variantGroup: "slots.state",
    file: "slots/locked.png",
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "공용 슬롯", note: "잠금 슬롯(자물쇠)" }],
  },
  {
    key: "meters.hp-bar",
    label: "HP Bar",
    sheet: F,
    category: "meters",
    file: "meters/hp-bar.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer/UnitDetail", note: "체력 바(수치 표기)" }],
  },
  {
    key: "meters.hp-gauge",
    label: "HP Gauge",
    sheet: F,
    category: "meters",
    file: "meters/hp-gauge.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "체력 게이지(% 표기)" }],
  },
  {
    key: "meters.mp-bar",
    label: "MP Bar",
    sheet: F,
    category: "meters",
    file: "meters/mp-bar.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/panels.ts", component: "renderUnitDetail", note: "마나 바" }],
  },
  {
    key: "meters.dark-energy-bar",
    label: "Dark Energy Bar",
    sheet: F,
    category: "meters",
    file: "meters/dark-energy-bar.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer/보스", note: "보스 특수 자원(다크 에너지)" }],
  },
  {
    key: "meters.boss-hp-bar",
    label: "Boss HP Bar",
    sheet: F,
    category: "meters",
    file: "meters/boss-hp-bar.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer", note: "보스 전용 대형 체력 바(상단 고정)" }],
  },
  {
    key: "meters.progress-bar",
    label: "Progress Bar",
    sheet: F,
    category: "meters",
    file: "meters/progress-bar.png",
    nineSlice: true,
    sliced: true,
    usage: [
      { module: "src/ui/panels.ts", component: "renderTopbar/Actionbar", note: "라운드 진행 바" },
      { module: "src/ui/modals.ts", component: "로딩/시뮬레이션", note: "범용 진행 바(%)" },
    ],
  },
  {
    key: "popups.tooltip",
    label: "Tooltip Box",
    sheet: F,
    category: "popups",
    file: "popups/tooltip.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/widgets.ts", component: "공용 툴팁", note: "스킬/아이템 설명 말풍선" }],
  },
  {
    key: "popups.confirm",
    label: "Confirm Popup",
    sheet: F,
    category: "popups",
    file: "popups/confirm.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/widgets.ts", component: "confirmModal", note: "예/아니오 확인 다이얼로그" }],
  },
  {
    key: "popups.reward",
    label: "Reward Popup",
    sheet: F,
    category: "popups",
    file: "popups/reward.png",
    nineSlice: true,
    sliced: true,
    usage: [
      { module: "src/ui/modals.ts", component: "openSelectorModal", note: "보상 수령 팝업(CLAIM)" },
      { module: "src/ui/modals.ts", component: "maybeShowResult", note: "런 종료 보상 요약" },
    ],
  },
  {
    key: "popups.boss-warning",
    label: "Boss Warning Popup",
    sheet: F,
    category: "popups",
    file: "popups/boss-warning.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/widgets.ts", component: "toast/openModal", note: "보스 등장 경고 팝업" }],
  },
  {
    key: "popups.boss-warning-banner",
    label: "Boss Warning Text Banner",
    sheet: C,
    category: "popups",
    file: "popups/boss-warning-banner.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/board.ts", component: "BoardRenderer/toast", note: "전장 상단 'BOSS APPROACHING!' 배너" }],
  },
  {
    key: "popups.settings",
    label: "Settings Popup",
    sheet: F,
    category: "popups",
    file: "popups/settings.png",
    nineSlice: true,
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "openOptionsOverlay", note: "설정(음악/사운드/보이스/품질) 팝업" }],
  },
  {
    key: "controls.checkbox.unchecked",
    label: "Checkbox Unchecked",
    sheet: F,
    category: "controls",
    variantGroup: "controls.checkbox",
    file: "controls/checkbox-unchecked.png",
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "openOptionsOverlay", note: "체크박스 해제" }],
  },
  {
    key: "controls.checkbox.checked",
    label: "Checkbox Checked",
    sheet: F,
    category: "controls",
    variantGroup: "controls.checkbox",
    file: "controls/checkbox-checked.png",
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "openOptionsOverlay", note: "체크박스 선택" }],
  },
  {
    key: "controls.toggle.off",
    label: "Toggle Button Off",
    sheet: F,
    category: "controls",
    variantGroup: "controls.toggle",
    file: "controls/toggle-off.png",
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "openOptionsOverlay", note: "토글 OFF" }],
  },
  {
    key: "controls.toggle.on",
    label: "Toggle Button On",
    sheet: F,
    category: "controls",
    variantGroup: "controls.toggle",
    file: "controls/toggle-on.png",
    sliced: true,
    usage: [{ module: "src/ui/scenes.ts", component: "openOptionsOverlay", note: "토글 ON" }],
  },
  {
    key: "controls.cursor",
    label: "Fantasy Mouse Cursor",
    sheet: F,
    category: "controls",
    file: "controls/cursor.png",
    sliced: true,
    usage: [{ module: "index.html / 전역 CSS", component: "body cursor", note: "전역 커스텀 커서" }],
  },
];

/** key로 단일 에셋 조회 */
export function getUiAsset(key: string): UiAsset | undefined {
  return UI_ASSETS.find((a) => a.key === key);
}

/** 카테고리별 그룹 조회 */
export function uiAssetsByCategory(category: AssetCategory): UiAsset[] {
  return UI_ASSETS.filter((a) => a.category === category);
}

/** 원본 시트별 그룹 조회 */
export function uiAssetsBySheet(sheet: SheetId): UiAsset[] {
  return UI_ASSETS.filter((a) => a.sheet === sheet);
}
